name: Build Executables

on:
  push:
    tags:
      - 'v*' 
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 matplotlib numpy pandas pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --noconsole --onefile --name VTC vtc.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VTC-${{ runner.os }}
        path: dist/*
